Repository numpy/numpydoc, pull requests merged in 2019-04, with the labels that each got.

#181 FIX pedantic handling of whitespace in reference regex
  numpydoc/numpydoc.py
Labels: bug

#175 FIX parsing of type-only return params
  numpydoc/docscrape.py
  numpydoc/docscrape_sphinx.py
  numpydoc/tests/test_docscrape.py
Labels: maintenance

#207 ENH: Allow a trailing COMMA or PERIOD in a See Also function list block
  numpydoc/docscrape.py
  numpydoc/tests/test_docscrape.py
Labels: maintenance

#161 Add option to use member listing for attributes
  doc/install.rst
  numpydoc/docscrape_sphinx.py
  numpydoc/numpydoc.py
  numpydoc/tests/test_docscrape.py
  numpydoc/tests/test_numpydoc.py
Labels: enhancement

#197 ENH: Xref param type
  .gitignore
  .travis.yml
  doc/Makefile
  doc/conf.py
  doc/example.py
  doc/install.rst
  numpydoc/docscrape_sphinx.py
  numpydoc/numpydoc.py
  numpydoc/tests/test_docscrape.py
  numpydoc/tests/test_numpydoc.py
  numpydoc/tests/test_xref.py
  numpydoc/xref.py
Labels: enhancement

#211 Updating minimum sphinx version in setup.py
  setup.py
Labels: maintenance
