Repository numpy/numpydoc, pull requests merged in 2023-08, with the labels that each got.

#483 Generate requirements files from pyproject.toml
  .pre-commit-config.yaml
  pyproject.toml
  requirements/developer.txt
  requirements/doc.txt
  requirements/test.txt
  tools/generate_pyproject.toml.py
  tools/generate_requirements.py
  tools/pyproject.toml.in
Labels: type: Maintenance

#488 Add config for pre-commit bot
  .pre-commit-config.yaml
Labels: type: Maintenance

#489 Use dependabot to update actions
  .github/dependabot.yml
Labels: type: Maintenance

#490 Update pydata-sphinx-theme
  .circleci/config.yml
  .github/workflows/test.yml
  pyproject.toml
  requirements/doc.txt
Labels: type: Maintenance

#491 Remove old linter check (using precommit bot now)
  .github/workflows/lint.yml
Labels: type: Maintenance

#476 Align behavior of pre-commit hook and Sphinx extension
  doc/install.rst
  doc/validation.rst
  numpydoc/hooks/validate_docstrings.py
  numpydoc/numpydoc.py
  numpydoc/tests/hooks/example_module.py
  numpydoc/tests/hooks/test_validate_hook.py
  numpydoc/tests/test_docscrape.py
  numpydoc/tests/test_numpydoc.py
  numpydoc/tests/test_validate.py
  numpydoc/validate.py
Labels: type: Enhancement

#492 Use label-check and attach-next-milestone-action
  .github/workflows/label-check.yml
  .github/workflows/milestone-merged-prs.yml
Labels: type: Maintenance

#493 TST: Test no-file for source
  .github/workflows/label-check.yml
  numpydoc/tests/test_validate.py
  numpydoc/validate.py
Labels: type: Bug fix

#499 Fix clean_backref for extensions that have backrefs to inline elements.
  numpydoc/numpydoc.py
  numpydoc/tests/test_numpydoc.py
Labels: type: Enhancement
