Repository numpy/numpydoc, pull requests merged in 2024-04, with the labels that each got.

#542 FIX: coroutines can have a return statement
  .circleci/config.yml
  .github/workflows/test.yml
  numpydoc/docscrape.py
  numpydoc/tests/test_docscrape.py
Labels: type: Bug fix

#540 DEV: Rm xfails from pytest summary.
  pyproject.toml
Labels: type: Maintenance

#549 Clean up old sphinx cruft
  numpydoc/numpydoc.py
  numpydoc/tests/tinybuild/conf.py
Labels: type: Maintenance

#547 Test on sphinx 7.3
  .circleci/config.yml
  .github/workflows/test.yml
Labels: type: Maintenance

#548 Classify development status as Production/Stable
  pyproject.toml
Labels: type: Documentation

#550 BUG: Fix bug with validation encoding
  .github/workflows/test.yml
Labels: type: Bug fix

#537 Unify CLIs
  .github/workflows/test.yml
  .pre-commit-hooks.yaml
  doc/validation.rst
  numpydoc/__main__.py
  numpydoc/cli.py
  numpydoc/hooks/validate_docstrings.py
  numpydoc/tests/hooks/test_validate_hook.py
  numpydoc/tests/test_main.py
  pyproject.toml
Labels: type: Enhancement
