Repository numpy/numpydoc, pull requests merged in 2024-03, with the labels that each got.

#531 Update precommit repos
  .pre-commit-config.yaml
Labels: type: Maintenance

#529 Add Python 3.12 to classifiers
  pyproject.toml
Labels: type: Documentation

#532 PERF: wrap inspect.getsourcelines with cache
  numpydoc/validate.py
Labels: type: Enhancement

#533 Use trusted publisher
  .github/workflows/release.yml
Labels: type: Maintenance

#534 Update release process
  RELEASE.rst
  doc/index.rst
  doc/release/index.rst
  doc/release/old.rst
  pyproject.toml
Labels: type: Documentation

#535 Update release process
  RELEASE.rst
Labels: type: Documentation

#538 Fix typo in label-check.yml
  .github/workflows/label-check.yml
Labels: type: Maintenance
