Repository numpy/numpydoc, pull requests merged in 2024-12, with the labels that each got.

#595 mention conda-forge in installation docs
  doc/install.rst
Labels: type: Documentation

#596 don't pass maxsplit as positional arg
  numpydoc/docscrape_sphinx.py
Labels: type: Maintenance

#593 ignore some errors at module level
  .gitignore
  numpydoc/__main__.py
  numpydoc/hooks/validate_docstrings.py
  numpydoc/tests/hooks/test_validate_hook.py
  numpydoc/tests/test_main.py
  numpydoc/validate.py
Labels: type: Enhancement
