Repository numpy/numpydoc, pull requests merged in 2025-06, with the labels that each got.

#628 Fix broken link in `format.rst`
  doc/format.rst
Labels: type: Documentation

#629 Fix pip setup command in github workflow
  .github/workflows/test.yml
Labels: type: Maintenance

#631 Specity the types of `numpydoc_xref_ignore` option
  numpydoc/numpydoc.py
Labels: type: Bug fix
